server:
  port: 8082

services:
  auth-service:
    url: http://autenticacion-seguridad:8081  # El nombre que pusiste en el compose

  user-service:
    url: http://usuarios-perfiles:8083        # El nombre que pusiste en el compose

logging:
  level:
    org.springframework.web: DEBUG