server:
  port: 8082

services:
  auth-service:
    url: http://autenticacion-seguridad:8081  # El nombre que pusiste en el compose

  user-service:
    url: http://usuarios-perfiles:8083        # El nombre que pusiste en el compose
  grades-service:
    url: http://ms-notas:8084

logging:
  level:
    org.springframework.web: DEBUG
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        record-exceptions:
          - java.lang.Exception
      auth-service:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        record-exceptions:
          - java.lang.Exception
      ms-usuarios:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        record-exceptions:
          - java.lang.Exception
      ms-notas:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        sliding-window-size: 10
        wait-duration-in-open-state: 30s
        record-exceptions:
          - java.lang.Exception
management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true